### ISSUE TITLE
Implement It in Windows Forms in C#

### ISSUE THREAD

**Issue by dev45** [SirTony/Pastebin.cs#5]
**Hi My Friend! could you send me an example of how to implement your code into a windows form in C# please?**

**Comment by craftersmine** [comment]
As a plugin for https://github.com/craftersmine/litescript_remastered

**Comment by clarajk** [comment]
A WinForms example will be included in the `Samples` directory when the project is updated as per #6

**Comment by CerebralMischief** [comment]
When? :P

**Comment by clarajk** [comment]
I no longer actively develop or maintain any of my C# projects, so unfortunately the answer is 'probably never'.

I'm still willing to review and merge pull requests should someone else wish to contribute. Although if there's still interest in this library it may be worth it just to fork the repo and continue development separately.
